// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    AInput: typeof import('ant-design-vue/es')['Input']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ContentOutput: typeof import('./src/components/yu-terminal/ContentOutput.vue')['default']
    Copy: typeof import('./src/components/Copy.vue')['default']
    Effects: typeof import('./src/components/effects.vue')['default']
    Loding: typeof import('./src/components/Loding.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    YuTerminal: typeof import('./src/components/yu-terminal/YuTerminal.vue')['default']
  }
}
